# Ievades ģeodati  {#Chapter3}

All chapters start with a first-level heading followed by your chapter title, like the line above. There should be only one first-level heading (`#`) per .Rmd file.

## Ievades jēldati {#Chapter3.1}

### Meža Valsts reģistrs {#Chapter3.1.1}

### Lauku atbalsts dienesta lauku informācija {#Chapter3.1.2}

### LĢIA topogrāfiskā karte {#Chapter3.1.3}

### MKIS {#Chapter3.1.4}

### LVM atvērtie dati {#Chapter3.1.5}

### Corine Land Cover {#Chapter3.1.6}

### Sentinel-2 {#Chapter3.1.7}

### *Dynamic World* {#Chapter3.1.8}

### *Global Forest Watch* {#Chapter3.1.9}

### Palsar Tree cover {#Chapter3.1.10}

### ERA-5 Land {#Chapter3.1.11}


### Augsnes auglīgums {#Chapter3.1.12}

### Digitālie reljefa modeļi {#Chapter3.1.13}


## Ievades produkti {#Chapter3.2}

### Reljefs {#Chapter3.2.1}

### Klimats {#Chapter3.2.2}

### Satelītindeksi {#Chapter3.2.3}

### Augsne {#Chapter3.2.4}


### Ainava {#Chapter3.2.5}

### Ceļi {#Chapter3.2.6}

### Eiklīda distances {#Chapter3.2.7}

### Malas {#Chapter3.2.8}

### Ūdeņi {#Chapter3.2.9}

### Lauksaimniecībā izmantojamās zemes {#Chapter3.2.10}

### Meži {#Chapter3.2.11}



## Vides pārmaiņas {#Chapter3.3}

Vides pārmaiņas nepieciešamas novērojumu filtrēšanai. Daļēji tās būtu iegūstamas no [Meža Valsts reģistrs](#Chapter3.1.1) un [LAD lauku informācija](#Chapter3.1.2) datiem, tomēr projekta darba grupā nav pieejami ik gada raksturojumi (1) un šīs datubāzes neaptver visu valsts teritoriju (2), tādēļ nepieciešams neatkarīgs vērtējums. Tāda izstrādāšanai izmantojām [*Dynamic World* izpēte](#Chapter4) aprīļa līdz augusta ik gada no 2016. līdz 2023. rezultātus un [*Global Forest Watch*](#Chapter3.1.9) datus, raksturojot pārmaiņu apjomus analīzes šūnā (nodaļa [100 m režģis Latvijā](#Chapter2.1)) un putnu ligzdošanas iecirkņu rādiusu grupu (\@ref(fig:AinavTelpas) att.) buferos ap analīzes šūnu centriem.

Šīs informācijas sagatavošanas gaita raksturota sekojošajās apakšnodaļās.

### *Dynamic World* {#Chapter3.3.1}

### Koku vainagu segums no Global forest watch {#Chapter3.3.2}

