# Ekoģeogrāfiskie mainīgie  {#Chapter5}

Šajā nodaļā apkopoti ekoģeogrāfisko mainīgo apraksti un sniegta pieeja to lejupielādei. Apkopotā formā ar hipersaitēm lejupielādei tā ir pieejama arī [šajā tabulā (xlsx)]().

Lai nedaudz atvieglotu pārskatīšanu, EGV grupēti pēc raksturojumu veida un prezentēti apakšnodaļās.

## Reljefs  {#Chapter5.1}

Reljefu raksturojošie un no DEM izrietošie EGV.

### DiS_area_r500

**Faila nosaukums un GeoTIFF pieejamība:** `.tif`, [RAW](), [centrēts un mērogots]()

**EGV nosaukums:**

**Izveidošanas gaita un atkarības:**


```{r, eval=FALSE}

```


## Klimats  {#Chapter5.2}

Klimatu un laika apstākļus raksturojošie EGV.


## Satelītindeksi  {#Chapter5.3}

Izmantojot Zemes novērošanas sistēmu spektrālos datus sagatavotie EGV.


## Augsne  {#Chapter5.4}


Augsni raksturojošie EGV.


## Ceļi  {#Chapter5.5}

Ceļus raksturojošie EGV.




## Malas  {#Chapter5.6}


Malas (ainavmetrikā) raksturojošie EGV.



## Ūdeņi  {#Chapter5.7}

Ūdeņus raksturojošie EGV.


## Lauki  {#Chapter5.8}

Laukus (lauksaimniecībā izmantojamās zemes) raksturojošie EGV.


## Meži  {#Chapter5.9}

Mežus raksturojošie EGV.



## Eiklīda distances  {#Chapter5.10}


Attālumu līdz ainavas objektiem raksturojošie EGV.


## Citi  {#Chapter5.11}

Pārējie EGV.


