# Novērojumu atlase {#Chapter6}

Šajā nodaļā raksturota novērojumu apkopošana un filtrēšana modelēšanai.

## Datu avoti {#Chapter6.1}

Dabasdati.lv

OZOLS - tikai daļa, bet jāpaņem no Life for Species

Aigars Kalvāns

DD&Co

Jānis Ķuze

Latvijas Dabas Fonds

Lediņš-Kalvāns-Jakovļevs

Edmunds Račinskis

Pūču plāna novērojumi

Pūču ligzdošanas vietas

Plēšputnu monitoringa ziņas

LPU 2023. gada dati

Vanagu projekta rezultāti

Piekrastes putnu monitorings(!)


## Nomenklatūra {#Chapter6.2}

Vārdnīcas katrai datu kopai

## Atrašanās Latvijā {#Chapter6.3}

Pret sapludināto 100 m režģi

## Datums un laiks {#Chapter6.4}

Kopš 2017. gada

Ne ilgāku periodu par 1 mēnesi

## Ligzdošanas pazīmes {#Chapter6.5}

Uz ligzdošanu attiecināmās pazīmes

## Dublieri {#Chapter6.6}

Ik datubāzē (arī - ja identifikatoram ir mainījie sugas nosaukums)

Starp datubāzēm

## Novietojums {#Chapter6.7}

Saskaņā ar CLC, izslēdzot droši nepiemēroto vidi

## Sezonalitāte {#Chapter6.8}

Ligzdošanas sezona, izņemot pierādītajām ligzdošanām

## Vides pārmaiņas {#Chapter6.9}

Analīzes šūnā nevienā periodā kopš novērojuma ne vairāk par 5% (10%?)

Ligzdošanas iecirknī ne vairāk par 10% (20%?)

## Papildkritēriji {#Chapter6.10}

Vismaz ACCGEN - attālums no apdzīvotām vietām


## Ligzdošanas ticamība {#Chapter6.11}

Ligzdošanas ticamības pakāpju pierēķināšana, lai izvēlētos uzticamākos, bet pietiekoša apjoma datus bez acīmredzamām telpiskajām problēmām

## Kvadrātu skaits {#Chapter6.12}

Pierēķināšana un vizualizēšana izvērtējumiem kopā ar ligzdošanas ticamības pakāpēm

## Rezultāti {#Chapter6.13}

Lēmumu pieņemšana par turpmāko modelēšanu un tai izmantojamajiem datiem

## Uzticamās klātbūtnes vietas {#Chapter6.14}

Failu saglabāšana