# SDM projekciju pēcapstrāde  {#Chapter8}

Pēc modeļu sagatavošanas veikta to izvērtēšana. Kā jau nereti, ne visi sagatavotie 
modeļi ir labi vai derīgi visiem iespējamajiem to lietošanas mērķiem, piemēram, 
individuālu sugu aizsardzības plānošanai šobrīd un projicēšanai nākotnē. Lai labāk 
saprastu modeļu spējas, visiem veikta vienota pēcapstrāde, kuras ietvaros veikta 
projicētās dzīvotņu piemērotības skalu pārveidošanas ([Projekciju pārveidošana](#Chapter8.1)), 
aprēķinātas atsevišķas projicētās dzīvotņu piemērotības indicētas sugas izplatības 
preferences ([Preferences](#Chapter8.2)) un sagatavota tabula, kurā apokpoti atsevišķi 
modeļu, projicētās dzīvotņu piemērotības un sugu izplatības raksturojumi, kopā ar 
indikatīvu modeļa novērtējumu izmantošanai vietu prioritizācijā aizsardzībai un 
daudzsugu prioritizācijā nepieciešamajai svarošanai vajadzīgajām vērtībām 
([Informatīvā tabula](#Chapter8.3)).


## Projekciju pārveidošana  {#Chapter8.1}

pārveidošanas

## Preferences  {#Chapter8.2}


Saistība ar ekosistēmām


Saistība ar aizsargājamām teritorijām


Saistība ar ES aizsargājamiem biotopiem



Saistība ar aizsardzības režīmiem


## Informatīvā tabula  {#Chapter8.3}


Ekoloģiskās nišas dziļumi

Pārējo vērtību ievietošana

Manuāli ievietotās vērtības

